"""empty message

Revision ID: 5aee6166d8af
Revises: f08b76b4a5d2
Create Date: 2021-12-08 16:55:47.898123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aee6166d8af'
down_revision = 'f08b76b4a5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('answer', 'created_date')
    op.add_column('question', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('question', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_date', sa.DATETIME(), nullable=False))
    op.drop_column('question', 'create_date')
    op.add_column('answer', sa.Column('created_date', sa.DATETIME(), nullable=False))
    op.drop_column('answer', 'create_date')
    # ### end Alembic commands ###
